[build.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "10.15.3"
[[redirects]]
  from = "/articles"
  to = "/blog"
  status = 301
[[redirects]]
  from = "/thesis.pdf"
  to = "/msc-thesis.pdf"
  status = 301