[build.environment]
  YARN_VERSION = "1.22.10"
  NODE_VERSION = "12.19.0"
[[redirects]]
  from = "/articles"
  to = "/blog"
  status = 301
[[redirects]]
  from = "/thesis.pdf"
  to = "/msc-thesis.pdf"
  status = 301
[[redirects]]
  from = "/curriculo.pdf"
  to = "/cv.pdf"
  status = 301
[[redirects]]
  from = "/curriculo"
  to = "/resume"
  status = 301