[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "10.15.3"
[[plugins]]
package = "netlify-plugin-gatsby-cache"
[[plugins]]
package = "netlify-plugin-hashfiles"
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
[[redirects]]
  from = "/articles"
  to = "/blog"
  status = 301