name: Run ESLint
on: pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Run eslint
        uses: tj-actions/eslint-changed-files@v8.4
        with:
          config_path: "./.eslintrc.js"
          ignore_path: "./.eslintignore"
          extra_args: "--max-warnings=0"