name: Check ESLint
on: pull_request

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install modules
        run: pnpm i
      - name: Run eslint
        uses: tj-actions/eslint-changed-files@v18.2
        with:
          config_path: './.eslintrc.js'
          ignore_path: './.eslintignore'
          extra_args: '--max-warnings=0'
