name: Unit tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install modules
        run: pnpm i
      - name: Run tests
        run: pnpm test:unit
