name: Unit tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install modules
        run: pnpm i
      - name: Run tests
        run: pnpm test:unit
