name: Unit tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install modules
        run: pnpm i
      - name: Run tests
        run: pnpm test:unit
