name: Unit tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install modules
        run: pnpm i
      - name: Run tests
        run: pnpm test:unit
